### ISSUE TITLE
Fix the nightmare `oneOf` hack

### ISSUE THREAD

**Issue by AnthonySuper** [SonderMindOrg/sober_swag#25]
Due to how OpenAPI definitions work, if you want to add *anything* separate from a ref to a field, you *must* wrap it in a `oneOf`. IE, this:

```yaml
fields:
  person:
    $ref: components/schemas/Person
    nullable: true
```

Doesn't work. It has to be:

```yaml
fields:
  person:
    oneOf:
      - $ref: components/schemas/Person
    nullable: true
```

We *currently* get around this by essentially saying "Screw it, just wrap all `$ref`s in a `oneOf`." But this leads to some *extremely* nasty API definitions with too much nesting, so we should probably handle this in a more robust way.

(Note: I personally think that *ever* using a `oneOf` with a single key is questionable, and that there should really be an alternative on the specification level. But whatever.)
